In [2]:
import numpy as np
arr1 = np.array([1,2,3])
print(arr1)

[1 2 3]


In [3]:
arr1[2]

3

In [4]:
arr1[2]= 5
arr1

array([1, 2, 5])

In [7]:
arr2 = np.array([[1,2,3], [4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [9]:
print("the shap is 2 rows and 3 columns:", arr2.shape)

the shap is 2 rows and 3 columns: (2, 3)


In [11]:
print(arr2[0][2])
print(arr2[0,2])
print(arr2[0,-1])
print(arr2[-1, 0])

3
3
3
4


In [12]:
arr3 = np.array(['india', 'china', 'usa', 'mexico'])
print(arr3)

['india' 'china' 'usa' 'mexico']


In [13]:
arr3[1]

'china'

In [15]:
arr = np.arange(0, 20, 2)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


In [16]:
arr = np.linspace(0, 10, 20)
print(arr)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [21]:
arr = np.random.rand(10)
print(arr)
print('\n')
arr = np.random.rand(3,4)
print(arr)

[0.62789063 0.99244055 0.02175457 0.72448904 0.76523443 0.01279822
 0.62870382 0.0540389  0.70008212 0.26196775]


[[0.11852374 0.0679539  0.27991389 0.07134177]
 [0.33686205 0.0658256  0.43355312 0.41526195]
 [0.1828888  0.44482912 0.40479366 0.02675526]]


In [22]:
print(np.full((4,6),10))

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]


In [23]:
arr = [0, 1, 2]
print(np.repeat(arr, 3))

[0 0 0 1 1 1 2 2 2]


In [24]:
arr = [0, 1, 2]
print(np.repeat(arr, 3))

[0 0 0 1 1 1 2 2 2]


In [25]:
arr = [0, 1, 2]
print(np.tile(arr, 3))

[0 1 2 0 1 2 0 1 2]


In [26]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [28]:
identity_matrix = np.identity(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [29]:
arr = np.random.rand(5,5)
print(arr)

[[0.77319439 0.16503536 0.59323327 0.64972808 0.90459091]
 [0.98725778 0.32335977 0.53439324 0.85879096 0.48523726]
 [0.48004488 0.25731082 0.78865382 0.24706963 0.55916247]
 [0.51950659 0.3074301  0.72280272 0.27059606 0.97250544]
 [0.14171828 0.22691596 0.80009026 0.51357007 0.00891106]]


In [30]:
print(np.sum(arr, axis=0))

[2.90172192 1.28005202 3.43917331 2.5397548  2.93040714]


In [31]:
print(np.sum(arr, axis=1))

[3.08578201 3.18903901 2.33224161 2.79284092 1.69120564]


In [32]:
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))

0.5236443673477816
0.5195065868443937
0.2737772375847655
0.07495397581954516


In [33]:
arr = np.random.rand(5,5)
print(arr)


[[0.89727802 0.2405532  0.40669447 0.58667453 0.33078314]
 [0.53557487 0.28107093 0.83734466 0.95746994 0.58426016]
 [0.08658229 0.03642672 0.22138387 0.49735388 0.20485092]
 [0.8249453  0.11798575 0.52410171 0.66137699 0.52867423]
 [0.69971007 0.34860757 0.86338481 0.63720149 0.26515891]]


In [34]:
print(np.sort(arr, axis=1))

[[0.2405532  0.33078314 0.40669447 0.58667453 0.89727802]
 [0.28107093 0.53557487 0.58426016 0.83734466 0.95746994]
 [0.03642672 0.08658229 0.20485092 0.22138387 0.49735388]
 [0.11798575 0.52410171 0.52867423 0.66137699 0.8249453 ]
 [0.26515891 0.34860757 0.63720149 0.69971007 0.86338481]]


In [35]:
arr = np.array([4,5,6,7])
arr1 = np.append(arr, 8)
arr1

array([4, 5, 6, 7, 8])

In [36]:
arr2 = np.append(arr, [9,10,11])
print(arr2)

[ 4  5  6  7  9 10 11]


In [37]:
arr2 = np.array([4,5,6,7,9,10,11])
print(arr2)
print('\n')
arr5 = np.delete(arr2, [1,4])
print(arr5)

[ 4  5  6  7  9 10 11]


[ 4  6  7 10 11]


In [38]:
arr1 = np.array([[1,2,3,4], [1,2,3,4]])
arr2 = np.array([[5,6,7,8], [5,6,7,8]])
cat = np.concatenate((arr1, arr2), axis=0)
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [39]:
cat =np.concatenate((arr1, arr2), axis=1)
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]
